# Generated by Django 5.0.3 on 2024-03-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manga_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="urls_images_list",
            field=models.JSONField(),
        ),
    ]
